# wrangler.toml
name = "quranradio"
main = "worker.js"
compatibility_date = "2025-09-14"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "public"
binding = "ASSETS"

[observability]
[observability.logs]
enabled = true
